window.UP = window.UP || {};

UP.WORDS5 = [
  "about","above","actor","acute","admit","adopt","after","again","agent","agree",
  "ahead","alarm","album","alert","alien","align","alike","alive","allow","alone",
  "along","alter","amber","amend","angel","anger","angle","angry","apart","apple",
  "apply","arena","argue","arise","array","arrow","aside","asset","audio","audit",
  "avoid","awake","award","aware","badly","baker","bases","basic","basis","beach",
  "began","begin","being","below","bench","birth","black","blame","blank","blast",
  "blaze","bleed","blend","bless","blind","block","blood","bloom","board","boast",
  "bonus","boost","booth","bound","brain","brand","brave","bread","break","breed",
  "brick","bride","brief","bring","broad","broke","brown","brush","build","built",
  "buyer","cabin","cable","camel","canal","candy","canoe","cargo","carry","catch",
  "cause","chain","chair","chalk","champ","chart","chase","cheap","check","chess",
  "chest","chief","child","china","choir","civil","claim","class","clean","clear",
  "clerk","click","cliff","climb","clock","close","cloth","cloud","coach","coast",
  "color","comic","coral","could","count","court","cover","craft","crash","crazy",
  "cream","creek","crime","crisp","cross","crowd","crown","crude","cruel","crush",
  "curve","cycle","daily","dairy","dance","dated","dealt","death","debut","delay",
  "delta","dense","depth","diary","digit","dirty","disco","ditch","doubt","dough",
  "draft","drain","drama","drank","drawn","dream","dress","dried","drift","drill",
  "drink","drive","drove","dummy","dune","early","earth","eight","elite","empty",
  "enemy","enjoy","enter","entry","equal","error","event","every","exact","exist",
  "extra","faith","false","fancy","fault","favor","feast","field","fifth","fifty",
  "fight","final","first","fixed","flame","flash","fleet","flesh","float","flood",
  "floor","flora","flour","fluid","focus","force","forth","found","frame","frank",
  "fresh","front","frost","fruit","fully","funny","giant","given","glass","globe",
  "glory","grace","grade","grain","grand","grant","grape","graph","grasp","grass",
  "grave","great","green","greet","grief","grind","gross","group","grove","grown",
  "guard","guess","guest","guide","habit","happy","harsh","heart","heavy","honey",
  "honor","horse","hotel","house","human","humor","hurry","ideal","image","index",
  "inner","input","issue","ivory","joint","judge","juice","known","label","labor",
  "large","laser","later","laugh","layer","learn","least","leave","legal","lemon",
  "level","light","limit","linen","liver","lobby","local","logic","loose","lucky",
  "lunar","lunch","magic","major","maker","maple","march","match","maybe","mayor",
  "medal","media","mercy","metal","meter","might","minor","minus","mixed","model",
  "money","month","moral","motor","mount","mouse","mouth","movie","music","naked",
  "nasty","naval","nerve","never","newer","newly","night","noble","noise","north",
  "noted","novel","nurse","occur","ocean","offer","often","olive","onion","opera",
  "orbit","order","organ","other","ought","outer","owner","oxide","paint","panel",
  "paper","party","peace","phase","phone","photo","piano","piece","pilot","pitch",
  "place","plain","plane","plant","plate","plaza","point","polar","pound","power",
  "press","price","pride","prime","print","prior","prize","proof","proud","prove",
  "queen","quick","quiet","quite","radio","raise","rally","range","rapid","ratio",
  "reach","react","ready","realm","rebel","refer","relax","reply","right","river",
  "robot","rough","round","route","royal","rural","salad","scale","scene","scope",
  "score","sense","serve","seven","shade","shake","shall","shame","shape","share",
  "sharp","sheep","sheet","shelf","shell","shift","shine","shirt","shock","shoot",
  "shore","short","shown","sight","sigma","skill","skull","sleep","slice","slide",
  "small","smart","smile","smoke","snake","solar","solid","solve","sorry","sound",
  "south","space","spare","speak","speed","spend","spice","spine","split","sport",
  "squad","stack","staff","stage","stake","stand","start","state","steam","steel",
  "steep","steer","stick","still","stock","stone","store","storm","story","strip",
  "stuck","study","stuff","style","sugar","suite","sunny","super","sweet","table",
  "taste","teach","thank","their","theme","there","thick","thief","thing","think",
  "third","those","three","throw","tiger","tight","timer","title","today","token",
  "tooth","topic","total","touch","tough","tower","track","trade","train","treat",
  "trend","trial","tribe","trick","tried","troop","truck","truly","trust","truth",
  "twice","under","union","unity","until","upper","urban","usage","usual","valid",
  "value","video","viral","visit","vital","vivid","voice","voter","waste","watch",
  "water","whale","wheat","wheel","where","which","while","white","whole","whose",
  "woman","world","worry","worth","would","wound","write","wrong","yield","young",
  "youth","zebra"
].filter((w) => w.length === 5);

UP.CONNECTIONS = [
  {
    groups: [
      { name: "Planets", color: "#f0c05a", words: ["MARS", "VENUS", "EARTH", "PLUTO"] },
      { name: "Shapes", color: "#a0c35a", words: ["CIRCLE", "SQUARE", "TRIANGLE", "HEXAGON"] },
      { name: "Indian rivers", color: "#b0c4ef", words: ["GANGA", "YAMUNA", "GODAVARI", "KAVERI"] },
      { name: "Chess pieces", color: "#ba81c5", words: ["KING", "QUEEN", "ROOK", "KNIGHT"] },
    ],
  },
  {
    groups: [
      { name: "Colors of the rainbow", color: "#f0c05a", words: ["RED", "ORANGE", "GREEN", "VIOLET"] },
      { name: "Sports", color: "#a0c35a", words: ["CRICKET", "HOCKEY", "TENNIS", "FOOTBALL"] },
      { name: "Units", color: "#b0c4ef", words: ["METRE", "GRAM", "LITRE", "SECOND"] },
      { name: "Tree parts", color: "#ba81c5", words: ["ROOT", "TRUNK", "LEAF", "BARK"] },
    ],
  },
  {
    groups: [
      { name: "Programming languages", color: "#f0c05a", words: ["PYTHON", "JAVA", "KOTLIN", "SWIFT"] },
      { name: "Gems", color: "#a0c35a", words: ["RUBY", "PEARL", "OPAL", "JADE"] },
      { name: "Birds", color: "#b0c4ef", words: ["EAGLE", "SWAN", "CROW", "PEACOCK"] },
      { name: "Kitchen", color: "#ba81c5", words: ["SPOON", "KNIFE", "PLATE", "STOVE"] },
    ],
  },
  {
    groups: [
      { name: "Indian festivals", color: "#f0c05a", words: ["HOLI", "DIWALI", "EID", "PONGAL"] },
      { name: "Oceans", color: "#a0c35a", words: ["PACIFIC", "ATLANTIC", "INDIAN", "ARCTIC"] },
      { name: "Musical notes", color: "#b0c4ef", words: ["DO", "RE", "MI", "FA"] },
      { name: "Body organs", color: "#ba81c5", words: ["HEART", "LIVER", "LUNGS", "BRAIN"] },
    ],
  },
  {
    groups: [
      { name: "Citrus fruits", color: "#f0c05a", words: ["ORANGE", "LEMON", "LIME", "GRAPEFRUIT"] },
      { name: "Weather", color: "#a0c35a", words: ["RAIN", "WIND", "HAIL", "SNOW"] },
      { name: "School subjects", color: "#b0c4ef", words: ["MATHS", "HISTORY", "PHYSICS", "ART"] },
      { name: "Farm animals", color: "#ba81c5", words: ["COW", "GOAT", "SHEEP", "HORSE"] },
    ],
  },
];

UP.REBUS = [
  { emojis: "🧈 🦋", answer: "butterfly", hint: "An insect" },
  { emojis: "🌞 🌸", answer: "sunflower", hint: "A tall yellow flower" },
  { emojis: "🌙 💡", answer: "moonlight", hint: "Night glow" },
  { emojis: "🔥 🚒", answer: "firetruck", alts: ["fire truck", "fire engine"], hint: "Emergency vehicle" },
  { emojis: "❄️ 👨", answer: "snowman", hint: "Winter figure" },
  { emojis: "⭐ 🐟", answer: "starfish", hint: "Sea creature" },
  { emojis: "🌧️ 🧥", answer: "raincoat", hint: "Wet-weather wear" },
  { emojis: "🦷 🧚", answer: "toothfairy", alts: ["tooth fairy"], hint: "Childhood legend" },
  { emojis: "📚 🐛", answer: "bookworm", hint: "Avid reader" },
  { emojis: "🏠 🐝", answer: "beehive", alts: ["bee hive"], hint: "Where honey is made" },
  { emojis: "👁️ 🍬", answer: "eyeball", alts: ["eye candy"], hint: "Two words also work" },
  { emojis: "🍍 🍎", answer: "pineapple", hint: "Tropical fruit" },
  { emojis: "🐈 🐟", answer: "catfish", hint: "A fish, or a fake profile" },
  { emojis: "🚪 🔔", answer: "doorbell", hint: "Visitors press it" },
  { emojis: "🧠 ⛈️", answer: "brainstorm", hint: "Idea session" },
  { emojis: "🍯 🌙", answer: "honeymoon", hint: "After a wedding" },
  { emojis: "🏀 🏟️", answer: "basketball", hint: "A sport" },
  { emojis: "⏰ 🔔", answer: "alarmclock", alts: ["alarm clock"], hint: "Wakes you up" },
];

UP.KEYWORDS = [
  { words: ["bark", "trunk", "oak", "leaf", "shade", "roots"], answer: "tree" },
  { words: ["pages", "spine", "author", "library", "novel", "chapter"], answer: "book" },
  { words: ["paw", "whiskers", "meow", "litter", "purr", "kitten"], answer: "cat" },
  { words: ["wave", "tide", "salt", "beach", "shark", "coral"], answer: "ocean", alts: ["sea"] },
  { words: ["crust", "slice", "toast", "loaf", "baker", "wheat"], answer: "bread" },
  { words: ["king", "rook", "pawn", "check", "board", "castle"], answer: "chess" },
  { words: ["orbit", "star", "comet", "galaxy", "nasa", "moon"], answer: "space" },
  { words: ["goal", "pitch", "offside", "striker", "fifa", "penalty"], answer: "football", alts: ["soccer"] },
  { words: ["petal", "pollen", "rose", "vase", "bloom", "garden"], answer: "flower" },
  { words: ["keyboard", "screen", "mouse", "cpu", "laptop", "code"], answer: "computer" },
  { words: ["yolk", "shell", "omelette", "hen", "white", "nest"], answer: "egg" },
  { words: ["thunder", "cloud", "umbrella", "monsoon", "puddle", "drizzle"], answer: "rain" },
  { words: ["scale", "gills", "fin", "aquarium", "hook", "trout"], answer: "fish" },
  { words: ["lens", "focus", "selfie", "flash", "album", "tripod"], answer: "camera", alts: ["photo"] },
  { words: ["stethoscope", "ward", "nurse", "surgery", "patient", "clinic"], answer: "hospital", alts: ["doctor"] },
];

UP.GK = [
  { q: "Which planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Mercury"], a: 1 },
  { q: "The River Ganga empties into which bay?", options: ["Bay of Bengal", "Arabian Sea", "Gulf of Kutch", "Palk Strait"], a: 0 },
  { q: "Who wrote the national anthem of India?", options: ["Bankim Chandra", "Rabindranath Tagore", "Sarojini Naidu", "Iqbal"], a: 1 },
  { q: "What is the chemical symbol for gold?", options: ["Gd", "Go", "Au", "Ag"], a: 2 },
  { q: "How many players are on a cricket team on the field?", options: ["9", "10", "11", "12"], a: 2 },
  { q: "The Taj Mahal was built by?", options: ["Akbar", "Shah Jahan", "Humayun", "Aurangzeb"], a: 1 },
  { q: "Which gas do plants absorb?", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], a: 2 },
  { q: "The smallest prime number is?", options: ["0", "1", "2", "3"], a: 2 },
  { q: "Which ocean is the largest?", options: ["Atlantic", "Indian", "Pacific", "Arctic"], a: 2 },
  { q: "H2O is the chemical formula of?", options: ["Salt", "Water", "Ozone", "Hydrogen"], a: 1 },
  { q: "India’s capital is?", options: ["Mumbai", "Kolkata", "New Delhi", "Chennai"], a: 2 },
  { q: "Which instrument measures temperature?", options: ["Barometer", "Thermometer", "Ammeter", "Hygrometer"], a: 1 },
  { q: "The first Prime Minister of India was?", options: ["Sardar Patel", "Jawaharlal Nehru", "Rajendra Prasad", "Lal Bahadur Shastri"], a: 1 },
  { q: "Light travels fastest in?", options: ["Water", "Air", "Glass", "Vacuum"], a: 3 },
  { q: "Which vitamin is produced in skin by sunlight?", options: ["A", "B12", "C", "D"], a: 3 },
  { q: "Mount Everest lies in which range?", options: ["Andes", "Alps", "Himalayas", "Rockies"], a: 2 },
  { q: "The currency of Japan is?", options: ["Yuan", "Won", "Yen", "Ringgit"], a: 2 },
  { q: "Which is a mammal that lays eggs?", options: ["Dolphin", "Platypus", "Whale", "Bat"], a: 1 },
  { q: "The hardest natural substance is?", options: ["Gold", "Iron", "Diamond", "Quartz"], a: 2 },
  { q: "Which festival is called the festival of lights?", options: ["Holi", "Diwali", "Onam", "Baisakhi"], a: 1 },
  { q: "CPU stands for?", options: ["Central Process Unit", "Central Processing Unit", "Computer Personal Unit", "Control Processing Unit"], a: 1 },
  { q: "The Suez Canal connects?", options: ["Red Sea & Mediterranean", "Atlantic & Pacific", "Black Sea & Caspian", "Arabian Sea & Bay of Bengal"], a: 0 },
  { q: "Who discovered gravity after a falling apple story?", options: ["Einstein", "Newton", "Galileo", "Kepler"], a: 1 },
  { q: "Which blood cells fight infection?", options: ["RBC", "WBC", "Platelets", "Plasma"], a: 1 },
  { q: "The longest bone in the human body is?", options: ["Tibia", "Femur", "Humerus", "Radius"], a: 1 },
  { q: "Which city is called the Pink City?", options: ["Udaipur", "Jaipur", "Jodhpur", "Bikaner"], a: 1 },
  { q: "Sound cannot travel through?", options: ["Water", "Steel", "Vacuum", "Air"], a: 2 },
  { q: "The Father of the Nation of India is?", options: ["Nehru", "Ambedkar", "Gandhi", "Bose"], a: 2 },
  { q: "Which planet has the most moons (among classic 8)?", options: ["Earth", "Mars", "Jupiter", "Venus"], a: 2 },
  { q: "Photosynthesis happens mainly in the?", options: ["Roots", "Leaves", "Flowers", "Bark"], a: 1 },
];

UP.CAPITALS = [
  { country: "India", capital: "New Delhi", flag: "🇮🇳" },
  { country: "Japan", capital: "Tokyo", flag: "🇯🇵" },
  { country: "France", capital: "Paris", flag: "🇫🇷" },
  { country: "Australia", capital: "Canberra", flag: "🇦🇺" },
  { country: "Brazil", capital: "Brasília", flag: "🇧🇷", alts: ["brasilia"] },
  { country: "Canada", capital: "Ottawa", flag: "🇨🇦" },
  { country: "Egypt", capital: "Cairo", flag: "🇪🇬" },
  { country: "Germany", capital: "Berlin", flag: "🇩🇪" },
  { country: "Italy", capital: "Rome", flag: "🇮🇹" },
  { country: "Kenya", capital: "Nairobi", flag: "🇰🇪" },
  { country: "Mexico", capital: "Mexico City", flag: "🇲🇽" },
  { country: "Nepal", capital: "Kathmandu", flag: "🇳🇵" },
  { country: "Pakistan", capital: "Islamabad", flag: "🇵🇰" },
  { country: "China", capital: "Beijing", flag: "🇨🇳" },
  { country: "Sri Lanka", capital: "Sri Jayawardenepura Kotte", flag: "🇱🇰", alts: ["colombo", "kotte"] },
  { country: "United Kingdom", capital: "London", flag: "🇬🇧" },
  { country: "United States", capital: "Washington, D.C.", flag: "🇺🇸", alts: ["washington", "washington dc"] },
  { country: "Spain", capital: "Madrid", flag: "🇪🇸" },
  { country: "South Korea", capital: "Seoul", flag: "🇰🇷" },
  { country: "Thailand", capital: "Bangkok", flag: "🇹🇭" },
  { country: "Turkey", capital: "Ankara", flag: "🇹🇷" },
  { country: "Bangladesh", capital: "Dhaka", flag: "🇧🇩" },
  { country: "South Africa", capital: "Pretoria", flag: "🇿🇦", alts: ["cape town", "bloemfontein"] },
  { country: "Russia", capital: "Moscow", flag: "🇷🇺" },
  { country: "Argentina", capital: "Buenos Aires", flag: "🇦🇷" },
  { country: "Indonesia", capital: "Jakarta", flag: "🇮🇩" },
  { country: "Saudi Arabia", capital: "Riyadh", flag: "🇸🇦" },
  { country: "Greece", capital: "Athens", flag: "🇬🇷" },
  { country: "Norway", capital: "Oslo", flag: "🇳🇴" },
  { country: "Sweden", capital: "Stockholm", flag: "🇸🇪" },
  { country: "Switzerland", capital: "Bern", flag: "🇨🇭", alts: ["berne"] },
  { country: "Portugal", capital: "Lisbon", flag: "🇵🇹" },
  { country: "Netherlands", capital: "Amsterdam", flag: "🇳🇱" },
  { country: "Ireland", capital: "Dublin", flag: "🇮🇪" },
  { country: "New Zealand", capital: "Wellington", flag: "🇳🇿" },
  { country: "Afghanistan", capital: "Kabul", flag: "🇦🇫" },
  { country: "Bhutan", capital: "Thimphu", flag: "🇧🇹" },
  { country: "Malaysia", capital: "Kuala Lumpur", flag: "🇲🇾" },
  { country: "Singapore", capital: "Singapore", flag: "🇸🇬" },
  { country: "Vietnam", capital: "Hanoi", flag: "🇻🇳" },
];

UP.TRUEFALSE = [
  { s: "The Great Wall of India is a real UNESCO site.", a: false },
  { s: "Humans have 206 bones as adults.", a: true },
  { s: "The Sun is a planet.", a: false },
  { s: "Water boils at 100°C at sea level.", a: true },
  { s: "Sharks are mammals.", a: false },
  { s: "The chemical symbol for iron is Fe.", a: true },
  { s: "Mount Kilimanjaro is in Asia.", a: false },
  { s: "Light year is a unit of time.", a: false },
  { s: "India has 28 states and 8 union territories.", a: true },
  { s: "The Pacific Ocean is salt-free.", a: false },
  { s: "Photosynthesis produces oxygen.", a: true },
  { s: "Zero is a natural number in every convention.", a: false },
  { s: "The Nile is in Africa.", a: true },
  { s: "Bats are blind.", a: false },
  { s: "Sound is faster than light.", a: false },
  { s: "The currency of India is the rupee.", a: true },
  { s: "Venus is hotter than Mercury.", a: true },
  { s: "A heptagon has eight sides.", a: false },
  { s: "DNA stands for deoxyribonucleic acid.", a: true },
  { s: "The Arctic is a continent.", a: false },
  { s: "Hockey is India’s national sport traditionally associated with the country.", a: true },
  { s: "Pi is exactly 22/7.", a: false },
  { s: "The moon has its own light.", a: false },
  { s: "Electrons are smaller than atoms.", a: true },
];

UP.HIGHERLOWER = [
  { name: "Population of India", value: 1400000000, unit: "people" },
  { name: "Population of USA", value: 340000000, unit: "people" },
  { name: "Height of Mount Everest", value: 8849, unit: "metres" },
  { name: "Speed of light", value: 299792458, unit: "m/s" },
  { name: "Days in a leap year", value: 366, unit: "days" },
  { name: "Olympic gold medals – USA (summer, all time ~)", value: 1060, unit: "medals" },
  { name: "Boiling point of water", value: 100, unit: "°C" },
  { name: "Melting point of ice", value: 0, unit: "°C" },
  { name: "Bones in adult human body", value: 206, unit: "bones" },
  { name: "Keys on a piano", value: 88, unit: "keys" },
  { name: "Squares on a chessboard", value: 64, unit: "squares" },
  { name: "Minutes in a day", value: 1440, unit: "minutes" },
  { name: "Countries in the UN (~)", value: 193, unit: "countries" },
  { name: "Atomic number of carbon", value: 6, unit: "" },
  { name: "Atomic number of gold", value: 79, unit: "" },
  { name: "Moons of Earth", value: 1, unit: "moon" },
  { name: "Players in a football team", value: 11, unit: "players" },
  { name: "Wonders of the ancient world", value: 7, unit: "" },
  { name: "Letters in English alphabet", value: 26, unit: "letters" },
  { name: "Hours in a week", value: 168, unit: "hours" },
  { name: "Distance Earth–Moon (avg)", value: 384400, unit: "km" },
  { name: "States in India", value: 28, unit: "states" },
  { name: "Teeth in adult human", value: 32, unit: "teeth" },
  { name: "World Cup cricket teams in 2023", value: 10, unit: "teams" },
];

UP.SYNONYMS = [
  { word: "BRAVE", type: "syn", options: ["BOLD", "TIMID", "WEAK", "SLOW"], a: 0 },
  { word: "HAPPY", type: "syn", options: ["SAD", "JOYFUL", "ANGRY", "TIRED"], a: 1 },
  { word: "BIG", type: "ant", options: ["HUGE", "LARGE", "SMALL", "GIANT"], a: 2 },
  { word: "FAST", type: "ant", options: ["QUICK", "RAPID", "SWIFT", "SLOW"], a: 3 },
  { word: "BEGIN", type: "syn", options: ["END", "START", "STOP", "CLOSE"], a: 1 },
  { word: "ANCIENT", type: "syn", options: ["OLD", "NEW", "FRESH", "MODERN"], a: 0 },
  { word: "ARRIVE", type: "ant", options: ["COME", "REACH", "DEPART", "ENTER"], a: 2 },
  { word: "GENEROUS", type: "ant", options: ["KIND", "STINGY", "NOBLE", "RICH"], a: 1 },
  { word: "SILENT", type: "syn", options: ["LOUD", "QUIET", "NOISY", "BUSY"], a: 1 },
  { word: "VICTORY", type: "ant", options: ["WIN", "TRIUMPH", "DEFEAT", "PRIZE"], a: 2 },
  { word: "ACCURATE", type: "syn", options: ["WRONG", "PRECISE", "ROUGH", "LATE"], a: 1 },
  { word: "EXPAND", type: "ant", options: ["GROW", "WIDEN", "SHRINK", "RISE"], a: 2 },
  { word: "CALM", type: "syn", options: ["PEACEFUL", "WILD", "ANGRY", "ROUGH"], a: 0 },
  { word: "PERMANENT", type: "ant", options: ["FIXED", "LASTING", "TEMPORARY", "STABLE"], a: 2 },
  { word: "ASSIST", type: "syn", options: ["HINDER", "HELP", "BLOCK", "DELAY"], a: 1 },
  { word: "SCARCE", type: "ant", options: ["RARE", "PLENTIFUL", "LITTLE", "FEW"], a: 1 },
  { word: "WISE", type: "syn", options: ["FOOLISH", "CLEVER", "NAIVE", "YOUNG"], a: 1 },
  { word: "ABOVE", type: "ant", options: ["OVER", "UP", "BELOW", "HIGH"], a: 2 },
  { word: "DANGER", type: "syn", options: ["SAFETY", "PERIL", "PEACE", "REST"], a: 1 },
  { word: "ACCEPT", type: "ant", options: ["TAKE", "RECEIVE", "REJECT", "ALLOW"], a: 2 },
];

UP.SEQUENCES = [
  { seq: [2, 4, 8, 16], options: [18, 24, 32, 20], a: 32, rule: "×2 each time" },
  { seq: [3, 6, 9, 12], options: [14, 15, 16, 18], a: 15, rule: "+3" },
  { seq: [1, 4, 9, 16], options: [20, 24, 25, 36], a: 25, rule: "squares" },
  { seq: [2, 3, 5, 8, 12], options: [15, 16, 17, 18], a: 17, rule: "+1, +2, +3, +4…" },
  { seq: [1, 1, 2, 3, 5], options: [7, 8, 9, 10], a: 8, rule: "Fibonacci" },
  { seq: [10, 20, 30, 40], options: [45, 50, 60, 70], a: 50, rule: "+10" },
  { seq: [81, 27, 9, 3], options: [2, 1, 0, 6], a: 1, rule: "÷3" },
  { seq: [5, 10, 20, 40], options: [60, 70, 80, 90], a: 80, rule: "×2" },
  { seq: [7, 14, 21, 28], options: [32, 35, 36, 42], a: 35, rule: "multiples of 7" },
  { seq: [1, 3, 6, 10], options: [12, 14, 15, 16], a: 15, rule: "triangular numbers" },
  { seq: [2, 6, 12, 20], options: [28, 30, 32, 24], a: 30, rule: "n(n+1)" },
  { seq: [100, 50, 25, 12.5], options: [10, 6.25, 5, 8], a: 6.25, rule: "÷2" },
  { seq: [4, 9, 16, 25], options: [30, 36, 49, 64], a: 36, rule: "squares starting 2²" },
  { seq: [11, 22, 33, 44], options: [54, 55, 56, 66], a: 55, rule: "+11" },
  { seq: [1, 8, 27, 64], options: [100, 125, 216, 81], a: 125, rule: "cubes" },
  { seq: [13, 17, 19, 23], options: [25, 27, 29, 31], a: 29, rule: "prime numbers" },
];

UP.ELEMENTS = [
  ["H", "Hydrogen", 1],
  ["He", "Helium", 2],
  ["Li", "Lithium", 3],
  ["C", "Carbon", 6],
  ["N", "Nitrogen", 7],
  ["O", "Oxygen", 8],
  ["F", "Fluorine", 9],
  ["Na", "Sodium", 11],
  ["Mg", "Magnesium", 12],
  ["Al", "Aluminium", 13],
  ["Si", "Silicon", 14],
  ["P", "Phosphorus", 15],
  ["S", "Sulfur", 16],
  ["Cl", "Chlorine", 17],
  ["K", "Potassium", 19],
  ["Ca", "Calcium", 20],
  ["Fe", "Iron", 26],
  ["Cu", "Copper", 29],
  ["Zn", "Zinc", 30],
  ["Ag", "Silver", 47],
  ["Au", "Gold", 79],
  ["Hg", "Mercury", 80],
  ["Pb", "Lead", 82],
  ["Ne", "Neon", 10],
];

UP.BEE = [
  {
    center: "A",
    letters: ["C", "L", "M", "P", "R", "T"],
    words: ["alpaca", "altar", "apart", "atlas", "calm", "camp", "carat", "cart", "clap", "cramp", "lama", "lamp", "mall", "malt", "map", "palm", "part", "ramp", "trap", "tram", "tact", "talc", "tramp", "pact", "mama", "papa", "call", "tall", "pall", "carp", "claptrap"],
  },
  {
    center: "E",
    letters: ["L", "N", "T", "R", "I", "G"],
    words: ["engine", "enter", "genre", "green", "greet", "elite", "entire", "gentle", "linger", "litre", "reign", "tiger", "tree", "teen", "reel", "ring", "tile", "lite", "genre", "nettle", "letter", "little", "elite", "girlie", "linen", "nine", "teen", "grin", "grin"],
  },
  {
    center: "O",
    letters: ["L", "N", "S", "T", "U", "B"],
    words: ["bonus", "boost", "loot", "lost", "lotus", "noun", "onto", "soon", "tool", "toon", "toss", "snub", "blot", "bolt", "bust", "lust", "nouns", "stool", "unbolt", "button", "cotton", "bloom", "nob", "sob", "ton", "sun", "bus", "but", "out", "soul", "snout", "blunt"],
  },
];

UP.SEARCH_THEMES = [
  { title: "Science", words: ["ATOM", "CELL", "GENE", "IRON", "MOON", "STAR", "HEAT", "WAVE"] },
  { title: "India", words: ["DELHI", "GANGA", "TAJ", "HOLI", "RUPEE", "HINDI", "GOA", "KERALA"] },
  { title: "Sports", words: ["GOAL", "BALL", "RACE", "TEAM", "WIN", "BAT", "COURT", "TRACK"] },
  { title: "Nature", words: ["TREE", "RIVER", "CLOUD", "LEAF", "BIRD", "SOIL", "RAIN", "WIND"] },
];

UP.NONOGRAMS = [
  {
    name: "Heart",
    grid: [
      [0,1,0,1,0],
      [1,1,1,1,1],
      [1,1,1,1,1],
      [0,1,1,1,0],
      [0,0,1,0,0],
    ],
  },
  {
    name: "Plus",
    grid: [
      [0,0,1,0,0],
      [0,0,1,0,0],
      [1,1,1,1,1],
      [0,0,1,0,0],
      [0,0,1,0,0],
    ],
  },
  {
    name: "Smile",
    grid: [
      [0,1,1,1,0],
      [1,0,1,0,1],
      [1,0,0,0,1],
      [1,0,0,0,1],
      [0,1,1,1,0],
    ],
  },
  {
    name: "Letter U",
    grid: [
      [1,0,0,0,1],
      [1,0,0,0,1],
      [1,0,0,0,1],
      [1,0,0,0,1],
      [0,1,1,1,0],
    ],
  },
  {
    name: "Boat",
    grid: [
      [0,0,1,0,0],
      [0,1,1,0,0],
      [1,1,1,1,1],
      [0,1,1,1,0],
      [0,0,1,0,0],
    ],
  },
];

UP.QUEENS = [
  {
    n: 6,
    colors: [
      [0,0,1,1,2,2],
      [0,3,3,1,2,4],
      [0,3,5,5,2,4],
      [3,3,5,4,4,4],
      [5,5,5,5,4,4],
      [5,5,5,5,5,4],
    ],
    solution: [[0,1],[1,3],[2,5],[3,0],[4,2],[5,4]],
  },
  {
    n: 5,
    colors: [
      [0,0,1,1,1],
      [0,2,2,1,3],
      [0,2,4,4,3],
      [2,2,4,3,3],
      [2,4,4,4,3],
    ],
    solution: [[0,1],[1,3],[2,0],[3,2],[4,4]],
  },
  {
    n: 6,
    colors: [
      [0,0,0,1,1,1],
      [0,2,2,2,1,3],
      [0,2,4,4,3,3],
      [5,2,4,3,3,3],
      [5,5,4,4,4,3],
      [5,5,5,5,4,4],
    ],
    solution: [[0,2],[1,4],[2,1],[3,5],[4,3],[5,0]],
  },
];

UP.ZIPS = [
  {
    n: 6,
    nums: { "0,0": 1, "2,3": 2, "5,5": 3, "0,5": 4, "5,0": 5 },
  },
  {
    n: 5,
    nums: { "0,0": 1, "0,4": 2, "4,4": 3, "4,0": 4, "2,2": 5 },
  },
  {
    n: 6,
    nums: { "1,1": 1, "1,4": 2, "4,4": 3, "4,1": 4, "2,2": 5, "3,3": 6 },
  },
];

UP.TWENTYFOUR = [
  [8, 3, 3, 3],
  [1, 3, 4, 6],
  [1, 1, 2, 7],
  [2, 2, 4, 7],
  [3, 3, 7, 7],
  [1, 5, 5, 5],
  [4, 4, 6, 8],
  [2, 5, 5, 10],
  [1, 6, 6, 8],
  [3, 3, 4, 8],
  [2, 3, 3, 12],
  [1, 4, 5, 6],
  [2, 2, 3, 8],
  [4, 5, 6, 7],
  [1, 2, 3, 8],
  [6, 6, 6, 6],
  [2, 4, 6, 8],
  [3, 5, 7, 9],
];
